// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQXnUawBlM2DrYlMSZmoyJxNmzj6DH2gc',
    appId: '1:768375306806:web:69750ced9b674782ec3697',
    messagingSenderId: '768375306806',
    projectId: 'agri-base-4ffb5',
    authDomain: 'agri-base-4ffb5.firebaseapp.com',
    storageBucket: 'agri-base-4ffb5.firebasestorage.app',
    measurementId: 'G-6NJMH1125J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCiImuSSF5AdD2yndf4ioYqLnVw90JV44',
    appId: '1:768375306806:android:02cf8c4b7d6e81baec3697',
    messagingSenderId: '768375306806',
    projectId: 'agri-base-4ffb5',
    storageBucket: 'agri-base-4ffb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBse42ceaiqpyNw8aMAPXWrTr1Khr0VzS4',
    appId: '1:768375306806:ios:3ee66a3b503d931dec3697',
    messagingSenderId: '768375306806',
    projectId: 'agri-base-4ffb5',
    storageBucket: 'agri-base-4ffb5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBse42ceaiqpyNw8aMAPXWrTr1Khr0VzS4',
    appId: '1:768375306806:ios:3ee66a3b503d931dec3697',
    messagingSenderId: '768375306806',
    projectId: 'agri-base-4ffb5',
    storageBucket: 'agri-base-4ffb5.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQXnUawBlM2DrYlMSZmoyJxNmzj6DH2gc',
    appId: '1:768375306806:web:9cd73690776aeb83ec3697',
    messagingSenderId: '768375306806',
    projectId: 'agri-base-4ffb5',
    authDomain: 'agri-base-4ffb5.firebaseapp.com',
    storageBucket: 'agri-base-4ffb5.firebasestorage.app',
    measurementId: 'G-H99FFMLVXX',
  );

}
